- name: Install Nginx Locally
  hosts: localhost
  become: yes 
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: stop nginx
      service:
        name: nginx
        state: stopped

    - name: Start Apache2
      service:
         name: apache2
         state: started
