- name: Install nginx and serve static website
  hosts: servers
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy Web page
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
